<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace Api\User\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.user.model.GetUserRes</code>
 */
class GetUserRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.api.user.model.User user = 1;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Api\User\Model\User $user
     * }
     */
    public function __construct($data = NULL) {
        \Api\User\GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.api.user.model.User user = 1;</code>
     * @return \Api\User\Model\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.api.user.model.User user = 1;</code>
     * @param \Api\User\Model\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Api\User\Model\User::class);
        $this->user = $var;

        return $this;
    }

}

