#!/usr/bin/env php
<?php

use Group\Sync\Console\Console;
use Group\Sync\SyncApp;

define('ASYNC', false);
define('__ROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");

$loader = require __DIR__.'/../vendor/autoload.php';

$loader->setUseIncludePath(true);

$app = new SyncApp();
$app -> initSelf();
$app -> registerServices();
$app -> singleton('container') -> setAppPath(__ROOT__);

$console = new Console($argv);
$console -> run();