#!/usr/bin/env php
<?php

use Group\Sync\Sync;
use Group\Sync\SyncApp;

define('ASYNC', FALSE);
define('__ROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");

$loader = require __DIR__.'/../vendor/autoload.php';
//$loader->setUseIncludePath(true);

$app = new SyncApp();
$app -> initSelf();
$provider = new Group\Sync\Cache\FileCacheServiceProvider($app::getInstance());
$provider -> register();

$async = new Sync($argv);
$async -> run();
